# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Revolute_6
      - Revolute_5
      - Revolute_4
      - Revolute_3
      - Revolute_2
      - Revolute_1
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      Revolute_1: {p: 500.0, i: 0.1, d: 10.0}
      Revolute_2: {p: 500.0, i: 0.1, d: 10.0}
      Revolute_3: {p: 500.0, i: 0.1, d: 10.0}
      Revolute_4: {p: 500.0, i: 0.1, d: 10.0}
      Revolute_5: {p: 500.0, i: 0.1, d: 10.0}
      Revolute_6: {p: 500.0, i: 0.1, d: 10.0}